name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "! contains(toJSON(github.event.head_commit.message), 'skip ci')"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php: ['7.2', '7.3', '7.4', '8.0', '8.1']
        include:
          - php: 7.2
            phpunit: 7
          - php: 7.3
            phpunit: 7
          - php: 7.4
            phpunit: 7
          - php: 8.0
            phpunit: 8
          - php: 8.1
            phpunit: 9
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache/files
        key: php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: php-${{ matrix.php }}-composer-

    - name: Install dependencies
      run: composer install --prefer-source

    - name: Fix possible style src
      run: composer lint-fix-src

    - name: Check style src
      if: failure()
      run: composer lint-src

    - name: Fix possible style test
      run: composer lint-fix-test

    - name: Check style test
      if: failure()
      run: composer lint-test

    - name: Run phan analysis
      run: composer analyze

    - name: Run tests
      run: composer test
